# spring.application.name=semester-result
spring.application.name=semester-result

server.port=8080

# ===============================
# MySQL Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/vit_result
spring.datasource.username=root
spring.datasource.password=Om_ugale_@701

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.cache=false